image: Ubuntu1804  # образ для сборки

stack: node 12  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name mosius27
  - git config --global user.email mosius27@yandex.ru
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$GITHUB_TOKEN:x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=build --branch=gh-pages --force --verbose